### ISSUE TITLE
Load Extension on Windows for DuckDB v0.10.0 fails

### ISSUE THREAD

**Issue by sipemu** [DataZooDE/erpl#15]
**Describe the bug**
Loading the ERPL extension on Windows fails for DuckDB version v0.10.0 

`Error: Invalid Input Error: Initialization function "erpl_init" from file "C:\Users\simon\.duckdb\extensions\v0.10.0\windows_amd64\erpl.duckdb_extension" threw an exception: "Failed to load ERPL RFC extension: IO Error: Extension "C:\Users\simon\.duckdb\extensions\v0.10.0\windows_amd64\erpl_rfc.duckdb_extension" could not be loaded: Das angegebene Modul wurde nicht gefunden.`

**To Reproduce**
Download Duckdb v0.10.0 from https://duckdb.org/ and extract it. Proceed with the following steps:

1. Start with `--unsigned` flag.
2. SET custom_extension_repository = 'http://get.erpl.io';
3. FORCE INSTALL erpl;
4. LOAD erpl.

Then the above error message should appear.

**Expected behavior**

The extension should be loaded successfully.

**Desktop (please complete the following information):**

- Windows 11

**Comment**

The extension for v0.10.0 works on Linux.

**Comment by jrosskopf** [comment]
It works for me on a fresh Windows 10 Pro. (really fresh).

- I installed duckdb via `winget install DuckDB.cli`
- This lead to first installing `Microsoft.VCRedist.2015+.x64`, which is a dependency of the DuckDB package.
- I also installed via `winget install Microsoft.VCRedist.2013.x64`, which is a dependency of the SAP Netweaver SDK

After that I could do:
![image](https://github.com/DataZooDE/erpl/assets/851749/85ca8a38-7889-4cbe-b742-c675846bd945)

What do you think, should we try to package:

- `msvcr120.dll`
- `msvcp120.dll`
- `mfc120.dll`
- `mfc120u.dll`
- `mfcm120.dll`
- `mfcm120u.dll`

Or should the user install the package and we document?
