### ISSUE TITLE
Add an example how to copy data to Motherduck

### ISSUE THREAD

**Issue by jrosskopf** [DataZooDE/erpl#16]
**Describe the solution you'd like**
I would like to have an example notebook showing how to transfer data via RFC, ODP or BICS to the cloud based Motherduck backend.

**Comment by gustavoleo** [comment]
I can work I that today

**Comment by gustavoleo** [comment]
Here is a sketch 
Please let me know if I`m to rigth path.
I want to contribute more


```
import duckdb
import pandas as pd


# Connect to a local DuckDB database 
con = duckdb.connect(database="/mnt/c/Users/GustavoLeo/Downloads/MotherDuck/sap_erpl_duckdb.duckdb", read_only=False)

# Set configurations necessary for ERPL extension
#con.execute("SET allow_unsigned_extensions = true;")
con.execute("SET custom_extension_repository = 'http://get.erpl.io';")


# Install and load the ERPL extension
con.execute("INSTALL erpl;")
con.execute("LOAD 'erpl';")

# Set SAP connection details
con.execute("""
    SET sap_ashost = 'localhost';
    SET sap_sysnr = '00';
    SET sap_user = 'DEVELOPER';
    SET sap_password = 'ABAPtr1909';
    SET sap_client = '001';
    SET sap_lang = 'EN';
""")

# Now, try to fetch data using the ERPL extension
try:
    df = con.execute("SELECT * FROM sap_read_table('SFLIGHT')").fetchdf()
    print("Data loaded into DataFrame successfully.")
    
    # Optionally, persist this DataFrame into the local DuckDB database
    con.register('sflight_data', df)
    con.execute("CREATE TABLE sflight_data AS SELECT * FROM sflight_data;")
    print("Data persisted into local DuckDB database.")
    
except Exception as e:
    print(f"Error fetching data: {e}")

con.close()

```

**Comment by sipemu** [comment]
I will write a blog post and add an example notebook to this repo.

**Comment by sipemu** [comment]
An example is added to our website: https://erpl.io/docs/cloud/sap_integration_motherduck.html

**Comment by gustavoleo** [comment]
> An example is added to our website: https://erpl.io/docs/cloud/sap_integration_motherduck.html

Maybe is good to mention that Motherduck works with version v0.9.2 only at this time

How about to include a point to check the actual verison at 

[https://motherduck.com/docs/getting-started/connect-query-from-python/installation-authentication](url)

The official quote is 

**MotherDuck currently supports DuckDB version v0.9.2 only. Support for v0.10.0 is coming soon!**

**Comment by sipemu** [comment]
@gustavoleo Thank you for the hint. I added a note on the page.
