### ISSUE TITLE
ERPL RFC extension not found

### ISSUE THREAD

**Issue by avocadokaracho** [DataZooDE/erpl#24]
**Describe the bug**
When installing I get the following message:
Invalid Input Error: Initialization function "erpl_init" from file "C:\...\v0.10.1\windows_amd64\erpl.duckdb_extension" threw an exception: "Failed to load ERPL RFC extension: IO Error: Extension "C:\...\v0.10.1\windows_amd64\erpl_rfc.duckdb_extension" could not be loaded: Das angegebene Modul wurde nicht gefunden. (aka module not found)

When I check the path, all expected files are present including "erpl_rfc.duckdb_extension"

**To Reproduce**
1. start "duckdb.exe -unsigned"
2. enter "SET custom_extension_repository = 'http://get.erpl.io';"
3. enter "INSTALL erpl;"
4. enter "LOAD erpl;"
5. See error

**Expected behavior**
Should install

**Screenshots**
-

**Desktop (please complete the following information):**
 - Win10 within cmd.exe

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by sipemu** [comment]
Hello @avocadokaracho,

That is a known issue. You need to execute `winget install Microsoft.VCRedist.2013.x64` in the command line as this package is needed by SAP Netweaver SDK. We will pack it into our extension in future version soon.

**Comment by avocadokaracho** [comment]
Hey sipemu,

thanks for your help. Loading works now!

Best regards,
avocado
