### ISSUE TITLE
Add OSX Apple Silicon Support

### ISSUE THREAD

**Issue by gregorwolf** [DataZooDE/erpl#36]
According to SAP Note [2573790 - Installation, Support and Availability of the SAP NetWeaver RFC Library 7.50](https://me.sap.com/notes/2573790) the SDK supports:

- Mac OS X 10.10, 10.11, 10.12, 10.13, 10.14, 10.15, 11, 12 X86_64 64bit
- Mac OS X 11, 12 ARM64 64bit

Also a link to the download is provided in this note.

**Comment by jrosskopf** [comment]
Hey @gregorwolf, thank you for the request. We are kind of on it ... I updated with the last iteration to the latest NWRFC SDK. And will try next to also get an OSX version of ERPL out. Bare with us for some days.

**Comment by jrosskopf** [comment]
@gregorwolf, wait for PR #37 to be merged, then ERPL should work on apple silicon:

![image](https://github.com/DataZooDE/erpl/assets/851749/5b00cbed-4300-46ac-943e-f075c8d6b2ff)
