### ISSUE TITLE
InvalidInputException: Invalid Input Error: Failed to cast value: Could not convert string " 1.24140-" to DECIMAL(9,5)

### ISSUE THREAD

**Issue by gustavoleo** [DataZooDE/erpl#5]
**Describe the bug**

Querying the table BKPF

con.sql("SELECT COUNT(MANDT) AS ROWS  FROM  sap_read_table('BKPF');")

┌────────┐
│  ROWS        │
│ int64            │
├────────┤
│ 411894        │
└────────┘

**To Reproduce**
con.sql("SELECT * FROM  sap_read_table('BKPF');")

**Expected behavior**

**Screenshots**

---------------------------------------------------------------------------
InvalidInputException                     Traceback (most recent call last)
File ~\AppData\Roaming\Python\Python311\site-packages\IPython\core\formatters.py:708, in PlainTextFormatter.__call__(self, obj)
    701 stream = StringIO()
    702 printer = pretty.RepresentationPrinter(stream, self.verbose,
    703     self.max_width, self.newline,
    704     max_seq_length=self.max_seq_length,
    705     singleton_pprinters=self.singleton_printers,
    706     type_pprinters=self.type_printers,
    707     deferred_pprinters=self.deferred_printers)
--> 708 printer.pretty(obj)
    709 printer.flush()
    710 return stream.getvalue()

File ~\AppData\Roaming\Python\Python311\site-packages\IPython\lib\pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File ~\AppData\Roaming\Python\Python311\site-packages\IPython\lib\pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

InvalidInputException: Invalid Input Error: Failed to cast value: Could not convert string " 1.24140-" to DECIMAL(9,5)

**Comment by sipemu** [comment]
The same error happens at other places in the Python example notebook:

`con.sql("SELECT * FROM sap_rfc_invoke('BAPI_FLIGHT_GETLIST', path='/FLIGHT_LIST')")`

`res = con.sql("SELECT * FROM sap_rfc_invoke('BAPI_FLIGHT_GETDETAIL', {'AIRLINEID': 'LH', 'CONNECTIONID': '0400', 'FLIGHTDATE': '2016-11-18'::DATE })").df()
`

**Comment by gustavoleo** [comment]
Any aditional logs needed?

(newtux) tony@lainoborgo:~/.duckdb/extensions$ ls
v0.10.0
---------------------------------------------------------------------------
InvalidInputException: Invalid Input Error: Failed to cast value: Could not convert string " 1.24140-" to DECIMAL(9,5)

**Comment by gustavoleo** [comment]
Super! @sipemu and @jrosskopf  works perfect now!
